name: Build Kernel

on:
  push:
    branches: [ Tweaks ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Clone toolchains
      run: |
        git clone https://github.com/FalconJaw/android-kernel-tools.git tools

    - name: Make build script executable
      run: chmod +x build_kernel.sh

    - name: Run build script
      run: ./build_kernel.sh

    - name: Upload compiled Image
      uses: actions/upload-artifact@v4
      with:
        name: Kernel Image
        path: arch/arm64/boot/Image
